#!/bin/bash
# Intended to be used on Fedora 30+ x86_64.
# Usage ./build-element <fedora version> <element version>
# Usage ./build-element 35 1.10.14
# Get version number here: https://github.com/vector-im/element-web/tags
# Requires mock, rpmi-build, wget, awk, tar, sed

# TODO fedpkg --release f35 mockbuild ??
# TODO rpmlint
# TODO configure less language packs??

if [ $1 -gt 1 ]; then
    FEDORA_VER="$1"
    MAJOR="$(echo $2 | awk -F '.' '{ print $1"."$2}')"
    MINOR="$(echo $2 | awk -F '.' '{ print $3}')"
    ELEMENT_VER="${MAJOR}.${MINOR}"
else
    curl https://raw.githubusercontent.com/vector-im/element-web/develop/CHANGELOG.md > changelog
    ELEMENT_VER=$(grep -o '\[[0-9]\.[0-9][0-9]\.[0-9]*\]' changelog | head -n 1 | tr -d [])
    FEDORA_VER="35"
    MAJOR="$(echo $ELEMENT_VER | awk -F '.' '{ print $1"."$2}')"
    MINOR="$(echo $ELEMENT_VER | awk -F '.' '{ print $3}')"
    echo "BUILD ELEMENT: $ELEMENT_VER on Fedora $FEDORA_VER"
    rm -f changelog
fi

function usage() {
    echo "Usage ./build-element (detects latest version automatically)"
    echo "Usage ./build-element <fedora version> <element version>"
    echo "Usage ./build-element 35 1.10.14"
}

if test -z $FEDORA_VER; then
    echo "Fedora version missing."
    usage
    exit 1
fi

if test -z $MAJOR; then
    echo "Element major version missing."
    usage
    exit 1
fi

if test -z $MINOR; then
    echo "Element minor version missing."
    usage
    exit 1
fi

echo "Building element: $ELEMENT_VER on $FEDORA_VER"

# Clear old archives 
rm -f ./SOURCES/*.gz

# Download new sources from element
wget https://github.com/vector-im/element-web/archive/refs/tags/v"${ELEMENT_VER}".tar.gz -O ./SOURCES/element-web-"${ELEMENT_VER}".tar.gz
wget https://github.com/vector-im/element-desktop/archive/refs/tags/v"${ELEMENT_VER}".tar.gz -O ./SOURCES/element-desktop-"${ELEMENT_VER}".tar.gz

# Download required olm package
mkdir ./SOURCES/get_olm
tar -xf ./SOURCES/element-web-*gz --directory ./SOURCES/get_olm
OLM=$(grep -o "https.*matrix-org/olm.*tgz" ./SOURCES/get_olm/element-web*/package.json)
echo "Required OLM package: $OLM"
wget "$OLM" 
mv olm*gz ./SOURCES/element-fedora
rm -rf ./SOURCES/get_olm

# Prepare fedora specific source tar from the fedora folder
tar -C ./SOURCES -czf ./SOURCES/element-fedora.tar.gz element-fedora
ls -lh ./SOURCES

# Prepare src.rpm from all the sources
cp element.spec build-element.spec
sed -i "s/define v_major [0-9].[0-9][0-9]/define v_major ${MAJOR}/" build-element.spec
sed -i "s/define v_minor [0-9]/define v_minor ${MINOR}/" build-element.spec
rpmbuild -v --define "_topdir $(pwd)" -bs build-element.spec
rm build-element.spec
mv ./SRPMS/*.src.rpm .
if ! test -e ./element*.src.rpm; then
    echo "ELEMENT BUILD FAILED"
    exit 1
fi

# Build the element package for set fedora version inside mock
mock --rootdir $(pwd)/mock -r fedora-${FEDORA_VER}-x86_64 --init
mock --rootdir $(pwd)/mock --resultdir $(pwd) --enable-network -r fedora-"${FEDORA_VER}"-x86_64 rebuild element-"${ELEMENT_VER}"-1*.src.rpm

# Clean up
mock --rootdir $(pwd)/mock -r fedora-"${FEDORA_VER}"-x86_64 --clean

mkdir -p version_history
rm ./element*.src.rpm
mv ./element*.rpm version_history

echo "Finished ${ELEMENT_VER} in ./version_history"
echo "$(pwd)/version_history/element-${ELEMENT_VER}-1.fc${FEDORA_VER}.x86_64.rpm"
echo "element-${ELEMENT_VER}-1.fc${FEDORA_VER}.x86_64.rpm" > ./latest.txt

rm -rf BUILD BUILDROOT RPMS SRPMS mock
rm -f ./SOURCES/*.gz
rm -f ./SOURCES/element-fedora/*.tgz
rm -f *.log *.src.rpm
